language: node_js
node_js:
  - "node"

env:
  DISCORD_KEY:
    secure: "H5h6Ky5KJQ8z68uV/bX23+KzU0v423Ed5nUbPVFE7GUXYDh6lPc61ZTPj6/pRIcn2jcafgNmxO3e5FgYfsmyqIGeLF/3vN9mCd+P01+Cawhuoa4qb+DIyvOd04LDYKiR8ynCVwUyyj+iG+28FBLvOkqfFfVmDpIgCoJtCvYn8pFFwa+z+tx6daM14hGON2FlFv6nxHR7V9xKZcgXRBjE5YRAROKqvHKI67XEm16JgcpX4DblGeDas5wjMIfGcJXws1ejEBgw32LVVk0NL/vP9uZ0Iywy8BLOHbugRvF2lnEWTix9naqg7KI2B9RY8ihKx5VSnZ/wz08f5aVecppKw2HgKmpK3oE5JxNF4rZ4gsyGWknjNUfULNhrCJx9W/tzdmBJsOXXpetZVFqV0+SDiVe6qlS5ODcI+Z4M//FKsjFPkySmMZa4JVK+7PeUS3W2tXq+HJZLySA5MdczmnO7ZmzPdH/RL39mL8/661eyubPp8P/woazTWn3J+84bPdzSoLck69UeLPUR8ftAik28+NVyabcFUps8cYAiIYxwM802ArvbNEQOmItruzLfQSqkMhQ6xTswPv70x4if8mkbsOuTTn75Dt5hLOohcDOJ4FnAvyFBb/kbdipv7hZopg/8bzd+RDgnJoCm7zoo7PhaPQxYNX4mCZX8p130dLi4rxY="